package main

import (
	"path/filepath"
	"strings"
)

// Lifecycle secrets are deliberately not generated by ensure or catalog
// upgrades. In particular an S3 access key cannot be fabricated locally, and
// lifecycle authority must be explicitly provisioned after qualification.
func billingLifecycleSecretCatalog() []secretCatalogEntry {
	rows := []struct{ id, consumer string }{
		{"cloud-logger-lifecycle-token", "cloud-logger"},
		{"cloud-logger-lifecycle-read-token", "cloud-logger,billing"},
		{"video-billing-raw-lifecycle-token", "video-cloud-mqttusage,billing"},
		{"billing-raw-retention-financial", "billing"},
		{"billing-raw-retention-recovery", "billing"},
		{"billing-raw-retention-controller", "billing"},
		{"billing-raw-retention-authority-read", "billing,cloud-logger"},
		{"billing-backup-access-key-id", "cloud-logger"},
		{"billing-backup-secret-access-key", "cloud-logger"},
	}
	out := make([]secretCatalogEntry, 0, len(rows))
	for _, row := range rows {
		consumers := strings.Split(row.consumer, ",")
		bindings, _ := billingLifecycleSecretBindings(row.id)
		out = append(out, secretCatalogEntry{ID: row.id, Category: "runtime", Consumers: consumers, Rotation: "explicit-manual", K8SBinding: bindings, Optional: true, ExplicitProvision: true})
	}
	return out
}

func billingLifecycleSecretBindings(id string) ([]secretK8SBinding, bool) {
	logger := func(key string) secretK8SBinding { return secretK8SBinding{"-logger", "cloud-logger-runtime", key} }
	billing := func(key string) secretK8SBinding {
		return secretK8SBinding{"-billing", "billing-raw-retention-runtime", key}
	}
	table := map[string][]secretK8SBinding{
		"cloud-logger-lifecycle-token":         {logger("RTK_CLOUD_LOGGER_BILLING_LIFECYCLE_TOKEN")},
		"cloud-logger-lifecycle-read-token":    {logger("RTK_CLOUD_LOGGER_BILLING_LIFECYCLE_READ_TOKEN"), billing("BILLING_RAW_RETENTION_LOGGER_TOKEN")},
		"video-billing-raw-lifecycle-token":    {{"-video-cloud", "video-cloud-billing-raw-lifecycle", "VIDEO_CLOUD_BILLING_RAW_LIFECYCLE_TOKEN"}, billing("BILLING_RAW_RETENTION_CONSUMER_TOKEN")},
		"billing-raw-retention-financial":      {billing("BILLING_RAW_RETENTION_FINANCIAL_TOKEN")},
		"billing-raw-retention-recovery":       {billing("BILLING_RAW_RETENTION_RECOVERY_TOKEN")},
		"billing-raw-retention-controller":     {billing("BILLING_RAW_RETENTION_CONTROLLER_TOKEN")},
		"billing-raw-retention-authority-read": {billing("BILLING_RAW_RETENTION_AUTHORITY_READ_TOKEN"), logger("RTK_CLOUD_LOGGER_BILLING_RETENTION_AUTHORITY_TOKEN")},
		"billing-backup-access-key-id":         {logger("RTK_CLOUD_LOGGER_BILLING_BACKUP_ACCESS_KEY_ID")},
		"billing-backup-secret-access-key":     {logger("RTK_CLOUD_LOGGER_BILLING_BACKUP_SECRET_ACCESS_KEY")},
	}
	bindings, ok := table[id]
	return bindings, ok
}

func billingLifecycleSecretID(id string) bool { _, ok := billingLifecycleSecretBindings(id); return ok }

func billingLifecycleSecretRequired(store secretStore, id string) bool {
	flags, err := billingLifecycleStoreFlags(store)
	if err != nil {
		return true
	} // Invalid intent must fail verification closed.
	switch id {
	case "billing-backup-access-key-id", "billing-backup-secret-access-key", "cloud-logger-lifecycle-token":
		return flags.Backup
	case "cloud-logger-lifecycle-read-token":
		return flags.Backup || flags.Authority
	default:
		return flags.Authority
	}
}

func billingLifecycleStoreFlags(store secretStore) (billingLifecycleFlags, error) {
	values := map[string]string{}
	if workspace, err := workspaceRoot(); err == nil {
		for _, file := range []string{"environment.env", "deployment.env", "storage.env"} {
			if entries, err := readStrictEnv(filepath.Join(workspace, "cloud_env", store.Environment, file)); err == nil {
				for key, value := range entries {
					values[key] = value
				}
			}
		}
	}
	// Operator values are the actual deploy overrides, not tracked templates.
	// Never read recovery/private-key custody trees when resolving enable flags.
	if operator, err := store.readOperator(); err == nil {
		for key, value := range operator {
			values[key] = value
		}
	}
	return lkeBillingLifecycleFlags(values)
}

func billingLifecycleBindingRequired(store secretStore, id string, binding secretK8SBinding) bool {
	if !billingLifecycleSecretID(id) {
		return true
	}
	flags, err := billingLifecycleStoreFlags(store)
	if err != nil {
		return true
	}
	if binding.Secret == "billing-raw-retention-runtime" || binding.Secret == "video-cloud-billing-raw-lifecycle" {
		return flags.Authority
	}
	if id == "cloud-logger-lifecycle-read-token" {
		return flags.Backup || flags.Authority
	}
	return flags.Backup && (id != "billing-raw-retention-authority-read" || flags.Authority)
}
