#!/usr/bin/env python3
"""Build and import sanitized canonical test report candidates."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]

ALLOWLISTED_REPORTS = {
    "LOAD_TEST_REPORT": Path("docs/LOAD_TEST_REPORT.md"),
}

REPORT_TITLES = {
    "LOAD_TEST_REPORT": "rtk_cloud_workspace E2E Load Test Report",
}

REQUIRED_HEADINGS = (
    "## Summary",
    "## Source Anchors",
    "## Environment",
    "## Commands",
    "## Result Summary",
    "## Detailed Results",
    "## Correctness / Behavior Gates",
    "## Coverage / Metrics",
    "## Skips And Blocks",
    "## Failures",
    "## Artifacts And Logs",
    "## Sign-off",
)

SECRET_PATTERNS = (
    re.compile(r"Authorization:\s*Bearer\s+(?!<redacted>)[^\s|,;]+", re.IGNORECASE),
    re.compile(r"(?i)\b(access|refresh|admin|account|device|stream)?_?token\s*=\s*(?!<redacted>)[^\s]+"),
    re.compile(r"(?i)\b(password|secret|api[_-]?key)\s*=\s*(?!<redacted>)[^\s]+"),
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"postgres://[^:\s]+:[^@\s]+@"),
)


class ReportCandidateError(RuntimeError):
    """Raised when a report candidate is unsafe or not importable."""


def canonical_path_for(report_type: str) -> Path:
    normalized = report_type.upper()
    try:
        return ALLOWLISTED_REPORTS[normalized]
    except KeyError as exc:
        allowed = ", ".join(sorted(ALLOWLISTED_REPORTS))
        raise ReportCandidateError(f"report type is not allowlisted: {report_type}; allowed: {allowed}") from exc


def sanitize_text(text: str) -> str:
    redacted = re.sub(
        r"Authorization:\s*Bearer\s+[^\s|,;]+",
        "Authorization: Bearer <redacted>",
        text,
        flags=re.IGNORECASE,
    )
    redacted = re.sub(
        r"(?i)\b(access|refresh|admin|account|device|stream)?_?token\s*=\s*[^\s]+",
        lambda match: f"{match.group(0).split('=')[0]}=<redacted>",
        redacted,
    )
    redacted = re.sub(
        r"postgres://[^:\s]+:[^@\s]+@",
        "postgres://<redacted>@",
        redacted,
    )
    return redacted


def assert_no_secret_like_text(text: str) -> None:
    for pattern in SECRET_PATTERNS:
        if pattern.search(text):
            raise ReportCandidateError(f"report candidate contains secret-like text: {pattern.pattern}")


def _repo_relative(path: Path) -> Path:
    resolved = path.resolve()
    try:
        return resolved.relative_to(REPO_ROOT)
    except ValueError:
        return path


def validate_candidate(
    *,
    report_type: str,
    candidate_path: Path,
    canonical_path: Path | None = None,
) -> None:
    expected = canonical_path_for(report_type)
    if canonical_path is not None:
        rel_canonical = _repo_relative(canonical_path)
        if rel_canonical.is_absolute() and len(rel_canonical.parts) >= 2:
            rel_canonical = Path(*rel_canonical.parts[-2:])
        if rel_canonical != expected:
            raise ReportCandidateError(
                f"expected canonical path {expected.as_posix()}, got {rel_canonical.as_posix()}"
            )
    if candidate_path.name != expected.name:
        raise ReportCandidateError(
            f"candidate filename {candidate_path.name} does not match {expected.name}"
        )
    text = candidate_path.read_text(encoding="utf-8")
    expected_title = REPORT_TITLES[report_type.upper()]
    if not text.startswith(f"# {expected_title}\n"):
        raise ReportCandidateError(f"candidate must start with '# {expected_title}'")
    assert_no_secret_like_text(text)
    missing = [heading for heading in REQUIRED_HEADINGS if heading not in text]
    if missing:
        raise ReportCandidateError(f"candidate is missing required headings: {', '.join(missing)}")


def build_candidate(
    *,
    report_type: str,
    output_path: Path,
    repository: str,
    report_id: str,
    source_report: Path | None,
    source_artifact: str,
    repository_commit: str,
    contracts_commit: str,
    prepared_by: str,
    automation_identity: str,
    report_class: str,
    overall_result: str,
    scope: str,
) -> None:
    normalized = report_type.upper()
    canonical_path_for(normalized)
    source_text = ""
    source_path_display = "N/A"
    if source_report is not None:
        source_text = sanitize_text(source_report.read_text(encoding="utf-8"))
        assert_no_secret_like_text(source_text)
        source_path_display = source_report.as_posix()

    title = REPORT_TITLES[normalized]
    lines = [
        f"# {title}",
        "",
        "## Summary",
        "",
        f"- Report ID: {report_id}",
        "- Created: generated by local or remote run; see source artifact timestamp",
        f"- Prepared by: {prepared_by}",
        f"- Automation identity: {automation_identity}",
        f"- Repository: {repository}",
        f"- Report class: {report_class}",
        f"- Overall result: {overall_result}",
        f"- Scope: {scope}",
        "",
        "## Source Anchors",
        "",
        f"- Repository commit: {repository_commit}",
        "- Repository branch or tag: workspace ref",
        "- Worktree state: N/A",
        "- Contracts repository: hkt999rtk/rtk_cloud_contracts_doc",
        f"- Contracts commit: {contracts_commit}",
        "- Contracts URL: repos/rtk_cloud_contracts_doc",
        "- Contract files referenced: N/A",
        "- PR / issue / release: N/A",
        "- Artifact version: N/A",
        "",
        "## Environment",
        "",
        "- Host: local, lab, or cloud load host",
        "- Host role: run-selected",
        "- OS: run-selected",
        "- Architecture: run-selected",
        "- Toolchains: see source artifact logs",
        "- Service dependencies: N/A unless source report says otherwise",
        "- Network profile: run-selected",
        "- Credentials source: CI secret | N/A",
        "- Secret handling note: canonical candidate is sanitized before import",
        "",
        "## Commands",
        "",
        "```sh",
        f"# Source report: {source_path_display}",
        f"# Source artifact: {source_artifact}",
        "python3 e2e_test/video_cloud/load/tools/report_candidate.py validate ...",
        "```",
        "",
        "## Result Summary",
        "",
        "| Category | PASS | FAIL | SKIP | BLOCKED | N/A |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
        f"| {report_class} | {'1' if overall_result == 'PASS' else '0'} | {'1' if overall_result == 'FAIL' else '0'} | 0 | {'1' if overall_result == 'BLOCKED' else '0'} | 0 |",
        "",
        "## Detailed Results",
        "",
        "| ID | Check | Result | Evidence | Duration | Notes |",
        "| --- | --- | --- | --- | --- | --- |",
        f"| REPORT-001 | Source report candidate | {overall_result} | {source_artifact} | N/A | Candidate generated from sanitized workflow report. |",
        "",
        "## Correctness / Behavior Gates",
        "",
        "| Behavior group | Required evidence | Representative test or command | Result | Notes |",
        "| --- | --- | --- | --- | --- |",
        f"| Report candidate import | allowlisted path, required headings, redaction validation | `e2e_test/video_cloud/load/tools/report_candidate.py validate` | {overall_result} | Raw logs stay artifact-only. |",
        "",
        "## Coverage / Metrics",
        "",
        "| Metric | Value | Threshold | Result | Notes |",
        "| --- | --- | --- | --- | --- |",
        "| Candidate coverage | 1 canonical report | 1 | PASS | This is report-import coverage, not code coverage. |",
        "",
        "## Skips And Blocks",
        "",
        "| Check | Result | Reason | Owner | Follow-up |",
        "| --- | --- | --- | --- | --- |",
        "| Raw logs in git | N/A | Raw logs remain uploaded artifacts, not tracked files. | repository | N/A |",
        "",
        "## Failures",
        "",
        "| Check | Failure summary | Suspected owner | Evidence | Follow-up issue / PR |",
        "| --- | --- | --- | --- | --- |",
        "| N/A | No failure recorded in this candidate envelope. | N/A | N/A | N/A |",
        "",
        "## Artifacts And Logs",
        "",
        f"- Report path: {canonical_path_for(normalized).as_posix()}",
        f"- Raw log directory: {source_artifact}",
        f"- Sanitized artifact directory: {output_path.parent.as_posix()}",
        "- CI artifact URL: sanitized artifact for the source run",
        "- Checksums: see source artifact when applicable",
        "- Redaction status: PASS",
        "",
        "## Sign-off",
        "",
        f"- Prepared by: {prepared_by}",
        "- Reviewed by: N/A",
        "- Accepted for PR / release / handoff: N/A",
        "- Acceptance notes: Candidate requires reviewer import/commit before it becomes canonical.",
        "",
    ]
    if source_text:
        lines.extend(
            [
                "<details>",
                "<summary>Sanitized source report excerpt</summary>",
                "",
                "```md",
                source_text[:6000],
                "```",
                "",
                "</details>",
                "",
            ]
        )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    validate_candidate(report_type=normalized, candidate_path=output_path)


def import_candidate(*, report_type: str, candidate_path: Path, repo_root: Path) -> Path:
    canonical = repo_root / canonical_path_for(report_type)
    validate_candidate(report_type=report_type, candidate_path=candidate_path, canonical_path=canonical)
    canonical.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(candidate_path, canonical)
    return canonical


def git_diff_check(repo_root: Path) -> None:
    completed = subprocess.run(
        ["git", "diff", "--check"],
        cwd=repo_root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if completed.returncode != 0:
        raise ReportCandidateError(completed.stdout.strip() or "git diff --check failed")


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    build = subparsers.add_parser("build")
    build.add_argument("--report-type", required=True)
    build.add_argument("--output", required=True, type=Path)
    build.add_argument("--repository", default="hkt999rtk/rtk_cloud_workspace")
    build.add_argument("--report-id", required=True)
    build.add_argument("--source-report", type=Path)
    build.add_argument("--source-artifact", default="N/A")
    build.add_argument("--repository-commit", required=True)
    build.add_argument("--contracts-commit", required=True)
    build.add_argument("--prepared-by", default="github-actions[bot]")
    build.add_argument("--automation-identity", default="manual or automation")
    build.add_argument("--report-class", required=True)
    build.add_argument("--overall-result", choices=("PASS", "FAIL", "BLOCKED"), required=True)
    build.add_argument("--scope", required=True)

    validate = subparsers.add_parser("validate")
    validate.add_argument("--report-type", required=True)
    validate.add_argument("--candidate", required=True, type=Path)
    validate.add_argument("--canonical", type=Path)

    import_cmd = subparsers.add_parser("import")
    import_cmd.add_argument("--report-type", required=True)
    import_cmd.add_argument("--candidate", required=True, type=Path)
    import_cmd.add_argument("--repo-root", default=REPO_ROOT, type=Path)

    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    try:
        if args.command == "build":
            build_candidate(
                report_type=args.report_type,
                output_path=args.output,
                repository=args.repository,
                report_id=args.report_id,
                source_report=args.source_report,
                source_artifact=args.source_artifact,
                repository_commit=args.repository_commit,
                contracts_commit=args.contracts_commit,
                prepared_by=args.prepared_by,
                automation_identity=args.automation_identity,
                report_class=args.report_class,
                overall_result=args.overall_result,
                scope=args.scope,
            )
        elif args.command == "validate":
            validate_candidate(
                report_type=args.report_type,
                candidate_path=args.candidate,
                canonical_path=args.canonical,
            )
        elif args.command == "import":
            import_candidate(
                report_type=args.report_type,
                candidate_path=args.candidate,
                repo_root=args.repo_root,
            )
            git_diff_check(args.repo_root)
        else:  # pragma: no cover
            raise ReportCandidateError(f"unknown command: {args.command}")
    except ReportCandidateError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
